name: GitHub Classroom Workflow

on: workflow_dispatch

env:
  GHSECRET: ${{ secrets.GITHUB_TOKEN }}
  COPY-ISSUES: "true"
  GRADING: "true"
  MOODLE: "true"

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  setup:
    if: ${{ contains(github.actor, 'classroom') }}
    uses: BZZ-Commons/workflows/.github/workflows/setup.yml@main
    with:
      SOURCE_REPO: templates-python/m319_lu04_a00_classroom
      TARGET_REPO: ${{ github.repository }}
      ADD_LABELS: "false"
    secrets:
      GHSECRET: ${{ secrets.GITHUB_TOKEN }}

  grading:
    if: ${{ !contains(github.actor, 'classroom') }}
    uses: BZZ-Commons/workflows/.github/workflows/grading.yml@main
    with:
      TARGET_REPO: ${{ github.repository }}
    secrets:
      GHSECRET: ${{ secrets.GITHUB_TOKEN }}
